# Generated by Django 2.0 on 2018-12-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='operate.Comment', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='message',
            name='replay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_replay', to='operate.Reply', verbose_name='回复'),
        ),
    ]
