# Generated by Django 2.0 on 2018-12-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0002_auto_20181209_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('letter', '私信'), ('invite', '邀请'), ('reply', '回复'), ('notice', '通知'), ('report', '举报'), ('feedback', '反馈')], max_length=10, verbose_name='消息类型'),
        ),
    ]
