# Generated by Django 2.0 on 2018-11-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0002_auto_20181103_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': '关注', 'verbose_name_plural': '关注'},
        ),
    ]
