# Generated by Django 2.0 on 2018-12-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20181130_1419'),
        ('operate', '0003_auto_20181213_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_activity', to='content.Activity', verbose_name='动态'),
        ),
        migrations.AlterField(
            model_name='message',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_agreement', to='content.Agreement', verbose_name='约拍'),
        ),
    ]
