# Generated by Django 2.0 on 2018-11-07 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181107_2040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operate', '0003_auto_20181103_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('content', models.TextField(verbose_name='内容')),
                ('answer', models.BooleanField(default=False, verbose_name='回答')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='content.Agreement', verbose_name='约拍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '发起',
                'verbose_name_plural': '发起',
            },
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_type',
        ),
        migrations.AddField(
            model_name='like',
            name='activity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.Activity', verbose_name='动态'),
            preserve_default=False,
        ),
    ]
