# Generated by Django 2.0 on 2018-11-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0004_auto_20181107_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='activity',
        ),
    ]
