# Generated by Django 2.0 on 2018-12-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0004_auto_20181213_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.Activity', verbose_name='评论的动态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.Agreement', verbose_name='评论的约拍'),
        ),
    ]
