# Generated by Django 2.0 on 2018-11-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181107_2040'),
        ('operate', '0005_remove_like_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.Activity', verbose_name='动态'),
            preserve_default=False,
        ),
    ]
