# Generated by Django 2.0 on 2018-12-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0005_auto_20181213_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='operate.Comment', verbose_name='评论'),
        ),
    ]
