# Generated by Django 2.0 on 2018-11-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0007_auto_20181108_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_nums',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='like_nums',
        ),
    ]
