# Generated by Django 2.0 on 2018-11-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0009_auto_20181112_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
