# Generated by Django 2.0 on 2018-11-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('image', models.ImageField(upload_to='image/content/%Y/%m', verbose_name='样张')),
            ],
            options={
                'verbose_name': '样张',
                'verbose_name_plural': '样张',
            },
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='like_nums',
        ),
        migrations.AddField(
            model_name='agreement',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='sample',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Agreement', verbose_name='样张'),
        ),
    ]
