# Generated by Django 2.0 on 2018-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20181108_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='image/topic/default.png', upload_to='image/topic/%Y/%m', verbose_name='图片'),
        ),
    ]
