# Generated by Django 2.0 on 2018-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='/image/topic/default.png', upload_to='image/topic/%Y/%m', verbose_name='图片'),
        ),
    ]
