# Generated by Django 2.0 on 2018-11-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.URLField(verbose_name='头像'),
        ),
    ]
