# Generated by Django 2.0 on 2018-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181104_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, verbose_name='性别'),
        ),
    ]
