# Generated by Django 2.0 on 2018-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181104_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '验证', 'verbose_name_plural': '验证'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.URLField(default='https://www.luoyangc.cn/static/favicon.ico', verbose_name='头像'),
        ),
    ]
