# Generated by Django 2.0 on 2018-11-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181111_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='simple_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/user/default.png', upload_to='image/user/%Y/%m', verbose_name='头像'),
        ),
    ]
