# Generated by Django 2.0 on 2018-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181119_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/image/user/default.png', upload_to='image/user/%Y/%m', verbose_name='头像'),
        ),
    ]
